name: try_upload

on: push

jobs:
  transfer:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "hello world" > /tmp/hello_world.txt
          echo "show you the world" > /tmp/world.txt

      - uses: actions/upload-artifact@v4
        with:
          name: lint-log
          path: |
            /tmp/hello_world.txt
            /tmp/world.txt

  see_tmp:
    runs-on: ubuntu-latest
    needs: transfer

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: lint-log
          path: /logs

      - name: Print log
        run: |
          ls /logs
          cat /logs/hello_world.txt
          cat /logs/world.txt

